services:
  trait-tracker:
    container_name: eso-crafting-traits
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GIT_COMMIT=local
    ports:
      - "8085:8080"
    restart: unless-stopped
    # No volumes needed (pure static build). Data is in users' browsers.
